[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/bridge',
    'pallets/bridge-transfer',
    'pallets/drop3',
    'pallets/extrinsic-filter',
    'primitives',
    'pallets/parachain-staking',
    'runtime/litentry',
    'runtime/litmus',
    'runtime/integration-tests',
]
